export const SKINCARES_ALL_REQUEST = 'SKINCARES_ALL_REQUEST'
export const SKINCARES_ALL_SUCCESS = 'SKINCARES_ALL_SUCCESS'
export const SKINCARES_ALL_FAIL = 'SKINCARES_ALL_FAIL'


export const SKINCARES_CREATE_REQUEST = 'SKINCARES_CREATE_REQUEST'
export const SKINCARES_CREATE_SUCCESS = 'SKINCARES_CREATE_SUCCESS'
export const SKINCARES_CREATE_FAIL = 'SKINCARES_CREATE_FAIL'
export const SKINCARES_CREATE_RESET = 'SKINCARES_CREATE_RESET'

export const SKINCARES_DELETE_REQUEST = 'SKINCARES_DELETE_REQUEST'
export const SKINCARES_DELETE_SUCCESS = 'SKINCARES_DELETE_SUCCESS'
export const SKINCARES_DELETE_FAIL = 'SKINCARES_DELETE_FAIL'



export const SKINCARES_BYID_REQUEST = 'SKINCARES_BYID_REQUEST'
export const SKINCARES_BYID_SUCCESS = 'SKINCARES_BYID_SUCCESS'
export const SKINCARES_BYID_FAIL = 'SKINCARES_BYID_FAIL'

export const SKINCARES_UPDATE_REQUEST = 'SKINCARES_UPDATE_REQUEST'
export const SKINCARES_UPDATE_SUCCESS = 'SKINCARES_UPDATE_SUCCESS'
export const SKINCARES_UPDATE_FAIL = 'SKINCARES_UPDATE_FAIL'
export const SKINCARES_UPDATE_RESET = 'SKINCARES_UPDATE_RESET'