export const STUDIO_INSERT_REQUEST = 'STUDIO_INSERT_REQUEST'
export const STUDIO_INSERT_SUCCESS = 'STUDIO_INSERT_SUCCESS'
export const STUDIO_INSERT_FAIL = 'STUDIO_INSERT_FAIL'

export const STUDIO_ALL_REQUEST = 'STUDIO_ALL_REQUEST'
export const STUDIO_ALL_SUCCESS = 'STUDIO_ALL_SUCCESS'
export const STUDIO_ALL_FAIL = 'STUDIO_ALL_FAIL'

export const STUDIO_BYID_REQUEST = 'STUDIO_BYID_REQUEST'
export const STUDIO_BYID_SUCCESS = 'STUDIO_BYID_SUCCESS'
export const STUDIO_BYID_FAIL = 'STUDIO_BYID_FAIL'

export const STUDIO_DELETE_REQUEST = 'STUDIO_DELETE_REQUEST'
export const STUDIO_DELETE_SUCCESS = 'STUDIO_DELETE_SUCCESS'
export const STUDIO_DELETE_FAIL = 'STUDIO_DELETE_FAIL'

export const STUDIO_UPDATE_REQUEST = 'STUDIO_UPDATE_REQUEST'
export const STUDIO_UPDATE_SUCCESS = 'STUDIO_UPDATE_SUCCESS'
export const STUDIO_UPDATE_FAIL = 'STUDIO_UPDATE_FAIL'
export const STUDIO_UPDATE_RESET = 'STUDIO_UPDATE_RESET'
